on: 
  push:
    branches:
      - 'prod'

jobs:
  publish:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    node-version: [16.x, 18.x]
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.1'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ screts.CLOUDFLARE_ACCOUNT_ID }}
          projectName: DanBSite
          directory: dist
          # enable to have GitHub Deployments triggered
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}